AWSTemplateFormatVersion: '2010-09-09'
Description: Infra Credentials Stack - Creates Redshift Master Password Secret

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - uat
      - prod

Resources:

  RedshiftMasterSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub redshift/${Environment}/master-password
      Description: Redshift master password
      GenerateSecretString:
        SecretStringTemplate: '{"username":"admin"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: '"@/\{}'

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub infra-agent-${AWS::AccountId}-${Environment}

      VersioningConfiguration:
        Status: Enabled

      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256      

Outputs:
  SecretName:
    Value: !Ref RedshiftMasterSecret
    Export:
      Name: !Sub redshift-${Environment}-secret-name